# Generated by Django 3.2.19 on 2023-08-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change_csv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cellvalue',
            old_name='value',
            new_name='name',
        ),
    ]
