# Generated by Django 3.2.19 on 2023-08-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_csv', '0002_rename_value_cellvalue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counteragent',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
