# Generated by Django 3.2.19 on 2023-08-27 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('change_csv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='change_csv.contacttype')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='change_csv.person')),
            ],
        ),
    ]
