# Generated by Django 3.2.19 on 2023-08-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change_csv', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
