# Generated by Django 3.2.19 on 2023-08-27 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change_csv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cellvalue',
            old_name='person',
            new_name='modelforbuild1',
        ),
        migrations.RenameField(
            model_name='cellvalue',
            old_name='contact_type',
            new_name='modelforbuild2',
        ),
    ]
