# Generated by Django 3.2.19 on 2023-08-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change_csv', '0002_contact_contacttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='parent',
        ),
    ]
