# Generated by Django 3.2.19 on 2023-08-27 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('change_csv', '0003_remove_person_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForBuild2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ContactType',
            new_name='ModelForBuild1',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RenameModel(
            old_name='Contact',
            new_name='CellValue',
        ),
        migrations.AlterField(
            model_name='cellvalue',
            name='contact_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='change_csv.modelforbuild2'),
        ),
    ]
