# Generated by Django 3.2.19 on 2023-08-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change_csv', '0003_auto_20230827_1501'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelForBuild1',
            new_name='Sdelka',
        ),
        migrations.RenameField(
            model_name='cellvalue',
            old_name='modelforbuild1',
            new_name='sdelka',
        ),
    ]
