# Generated by Django 3.2.19 on 2023-08-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change_csv', '0005_alter_contacttype_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='CellValue',
        ),
        migrations.RenameModel(
            old_name='Person',
            new_name='ModelForBuild1',
        ),
        migrations.RenameModel(
            old_name='ContactType',
            new_name='ModelForBuild2',
        ),
    ]
